# Generated by Django 4.2.4 on 2023-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerTIN', models.CharField(max_length=20)),
                ('LicenceNumber', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
