# Generated by Django 4.2.4 on 2023-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='LicenceNumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OwnerTIN',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
